name: MuColl Image Build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mucoll-image:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/muoncollidersoft/mucoll-ml-ubuntu24:full_gaudi_test
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
          testing: false
      - uses: actions/checkout@v5
        with:
          path: MLTracking
      - name: Build dependencies
        run: |
          . /opt/spack/opt/spack/*/*/*/*/*/mucoll-stack-full-gaudi-test-*/setup.sh
          . MLTracking/build_dependencies.sh
      - name: Build
        run: |
          . /opt/spack/opt/spack/*/*/*/*/*/mucoll-stack-full-gaudi-test-*/setup.sh
          . MLTracking/setup_dependencies.sh
          cd MLTracking
          cmake -B build -S . \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/install \
            -DCMAKE_CXX_STANDARD=20
          cmake --build build
